---

- name: Copy docker compose and settings files
  ansible.builtin.copy:
    src: "files/{{ item.src }}"
    dest: "{{ monitoring_install_path }}/{{ item.dest }}"
    owner: "{{ ctf_user }}"
    group: "{{ ctf_user }}"
    mode: "0644"
  become: true
  become_user: "{{ ctf_user }}"
  loop:
    - { src: "docker-compose.exporter.yml", dest: "docker-compose.yml" }

- name: Start monitor cAdvisor docker-compose
  ansible.builtin.shell: "docker compose up -d --build --force-recreate"
  args:
    chdir: "{{ monitoring_install_path }}"
  register: exporter_compose_output
  changed_when: "'recreated' in exporter_compose_output.stdout or 'Pulling' in exporter_compose_output.stdout"
  become: true
  become_user: "{{ ctf_user }}"
