---

- name: "Create '{{ monitoring_install_path }}' directory"
  ansible.builtin.file:
    path: "{{ monitoring_install_path }}"
    state: directory
    owner: "{{ ctf_user }}"
    group: "{{ ctf_user }}"
  become: true
  become_user: "{{ ctf_user }}"

- name: Setup Panel
  ansible.builtin.import_tasks:
    file: panel.yml
  when: inventory_hostname in groups['deploy-dynamic']

- name: Setup Exporter
  ansible.builtin.import_tasks:
    file: exporter.yml
  when: inventory_hostname not in groups['deploy-dynamic']
