---

- name: Setup Git repository of challenges
  ansible.builtin.import_tasks:
    file: git_repository.yml

- name: Setup docker configuration for dynamic challenges
  ansible.builtin.import_tasks:
    file: dynamic_docker_config.yml
  when: inventory_hostname in groups['dynamic-challenges']
