---

- name: Download Docker installation script
  ansible.builtin.get_url:
    url: https://get.docker.com/
    dest: "{{ ansible_env.HOME }}/install-docker.sh"
    mode: '0755'
  become: true

- name: Run Docker installation script
  ansible.builtin.command: "{{ ansible_env.HOME }}/install-docker.sh"
  become: true

- name: "Add 'docker' group to '{{ ctf_user }}'"
  ansible.builtin.user:
    name: "{{ ctf_user }}"
    groups: docker
    append: true
  become: true

- name: Enable and start docker
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
  become: true
