---

- name: Update APT repositories
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Install usefull packages
  ansible.builtin.apt:
    pkg:
      - vim
      - git
      - unzip
      - p7zip-full
      - curl
      - wget
      - netcat-openbsd
      - net-tools
      - acl # required by ansible to become an unprivileged user
      - gnupg # required to add docker's repository
  become: true
