---

- name: "Clone CTFd at version '{{ ctfd_version }}' to '{{ ctfd_install_path }}'"
  ansible.builtin.git:
    repo: "https://github.com/CTFd/CTFd.git"
    dest: "{{ ctfd_install_path }}"
    version: "{{ ctfd_version }}"
    force: true
  become: true
  become_user: "{{ ctf_user }}"

- name: "Copy '.env' to '{{ ctfd_install_path }}/.env'"
  ansible.builtin.copy:
    src: "files/.env"
    dest: "{{ ctfd_install_path }}/.env"
    owner: "{{ ctf_user }}"
    group: "{{ ctf_user }}"
    mode: "0644"
  become: true

- name: "Copy 'docker-compose.yml.j2' to '{{ ctfd_install_path }}/docker-compose.yml'"
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ ctfd_install_path }}/docker-compose.yml"
    owner: "{{ ctf_user }}"
    group: "{{ ctf_user }}"
    mode: "0644"
  become: true
  become_user: "{{ ctf_user }}"

- name: "Copy 'http.conf.j2' to '{{ ctfd_install_path }}/conf/nginx/http.conf'"
  ansible.builtin.template:
    src: "http.conf.j2"
    dest: "{{ ctfd_install_path }}/conf/nginx/http.conf"
    owner: "{{ ctf_user }}"
    group: "{{ ctf_user }}"
    mode: "0644"
  become: true

- name: "Create a 'certs' directory for HTTPs certificates"
  ansible.builtin.file:
    path: "{{ ctfd_install_path }}/conf/nginx/certs/"
    state: directory
    owner: "{{ ctf_user }}"
    group: "{{ ctf_user }}"
    mode: "0775"
  become: true

- name: "Copy 'fullchain.pem' & 'privkey.pem' to '{{ ctfd_install_path }}/conf/nginx/certs/'"
  ansible.builtin.copy:
    src: "files/certs/{{ item }}"
    dest: "{{ ctfd_install_path }}/conf/nginx/certs/{{ item }}"
    owner: "{{ ctf_user }}"
    group: "{{ ctf_user }}"
    mode: "0644"
  loop:
    - fullchain.pem
    - privkey.pem
  become: true

- name: "Copy '{{ ctfd_dkim_private_key }}' to '{{ ctfd_install_path }}/conf/'"
  ansible.builtin.copy:
    src: "files/{{ ctfd_dkim_private_key }}"
    dest: "{{ ctfd_install_path }}/conf/{{ ctfd_dkim_private_key }}"
    owner: "{{ ctf_user }}"
    group: "{{ ctf_user }}"
    mode: "0644"
  when: ctfd_install_dkim
  become: true

- name: "Copy 'CTFd_smtp.py' for DKIM configuration"
  ansible.builtin.copy:
    src: "files/CTFd_v{{ ctfd_version }}_smtp.py"
    dest: "{{ ctfd_install_path }}/CTFd/utils/email/providers/smtp.py"
    owner: "{{ ctf_user }}"
    group: "{{ ctf_user }}"
    mode: "0644"
  when: ctfd_install_dkim
  become: true

- name: "Copy 'CTFd_api_v1_challenges.py' for first blood Discord webhook"
  ansible.builtin.copy:
    src: "files/CTFd_v{{ ctfd_version }}_api_v1_challenges.py"
    dest: "{{ ctfd_install_path }}/CTFd/api/v1/challenges.py"
    owner: "{{ ctf_user }}"
    group: "{{ ctf_user }}"
    mode: "0644"
  when: ctfd_install_discord_webhook
  become: true

- name: "Copy 'CTFd_config.py' for better connection settings with the database"
  ansible.builtin.copy:
    src: "files/CTFd_v{{ ctfd_version }}_config.py"
    dest: "{{ ctfd_install_path }}/CTFd/config.py"
    owner: "{{ ctf_user }}"
    group: "{{ ctf_user }}"
    mode: "0644"
  become: true

- name: Extract the custom theme
  ansible.builtin.unarchive:
    src: "files/{{ ctfd_theme_name }}"
    dest: "{{ ctfd_install_path }}/CTFd/themes/"
  become: true
  become_user: "{{ ctf_user }}"
  when: ctfd_install_theme

- name: "Create directories for docker-compose volumes"
  ansible.builtin.file:
    path: "{{ ctfd_install_path }}/{{ item }}"
    state: directory
    owner: "{{ ctf_user }}"
    group: "{{ ctf_user }}"
    mode: "0777"
    recurse: true
  loop:
    - data/
    - data/postgres/
    - data/redis/
  become: true

- name: "Add 'psycopg2-binary' and 'dkimpy' to requirements.txt"
  ansible.builtin.shell: "echo 'psycopg2-binary\ndkimpy' >> requirements.txt"
  args:
    chdir: "{{ ctfd_install_path }}"
  become: true
  become_user: "{{ ctf_user }}"

- name: Start CTFd docker-compose
  ansible.builtin.shell: "docker compose up -d --build"
  args:
    chdir: "{{ ctfd_install_path }}"
  register: ctfd_docker_compose_output
  changed_when: "'recreated' in ctfd_docker_compose_output.stdout or 'Pulling' in ctfd_docker_compose_output.stdout"
  become: true
  become_user: "{{ ctf_user }}"
